export const FGB_DEFAULT_FEES = [
  { key: 'FILIACAO', label: 'Taxa de Filiacao', value: 1000.0, category: 'FILIACAO', description: 'Art. 2o - Taxa unica de filiacao ao quadro da FGB' },
  { key: 'ANUIDADE', label: 'Anuidade', value: 2500.0, category: 'FILIACAO', description: 'Art. 2o - Anuidade de manutencao de filiacao' },
  { key: 'LICENCIAMENTO', label: 'Licenciamento', value: 650.0, category: 'FILIACAO', description: 'Art. 2o - Taxa de licenciamento' },
  { key: 'ANUIDADE_LICENCIAMENTO', label: 'Anuidade de Licenciamento', value: 1000.0, category: 'FILIACAO', description: 'Art. 2o - Renovacao anual de licenciamento' },
  { key: 'DESFILIACAO', label: 'Desfiliacao', value: 1000.0, category: 'FILIACAO', description: 'Art. 2o - Taxa de desfiliacao' },
  { key: 'REGISTRO_ATLETA', label: 'Registro/Renovacao de Atleta', value: 50.0, category: 'INSCRICAO', description: 'Art. 3o - Por atleta acima da cota de 12 isentos + 1 tecnico por categoria' },
  { key: 'ATLETAS_ISENTOS_POR_CATEGORIA', label: 'Atletas isentos por categoria', value: 12, category: 'INSCRICAO', description: 'Art. 3o - Ate 12 atletas + 1 tecnico isentos por categoria' },
  { key: 'TRANSFERENCIA_INTRA_ESTADO', label: 'Transferencia entre clubes do Estado', value: 130.0, category: 'TRANSFERENCIA', description: 'Art. 4o - a) Entre clubes do Estado' },
  { key: 'TRANSFERENCIA_ENTRE_FEDERACOES_CBB', label: 'Transferencia entre Federacoes (taxa CBB)', value: 200.0, category: 'TRANSFERENCIA', description: 'Art. 4o - b) Entrada no Estado - taxa CBB' },
  { key: 'TRANSFERENCIA_ENTRE_FEDERACOES_FGB', label: 'Transferencia entre Federacoes (taxa FGB)', value: 130.0, category: 'TRANSFERENCIA', description: 'Art. 4o - b) Entrada no Estado - taxa FGB' },
  { key: 'TRANSFERENCIA_INTERNACIONAL_CBB_MIN', label: 'Transferencia Internacional (CBB minimo)', value: 1000.0, category: 'TRANSFERENCIA', description: 'Art. 4o - c) Internacional - taxa CBB minima' },
  { key: 'TRANSFERENCIA_INTERNACIONAL_CBB_MAX', label: 'Transferencia Internacional (CBB maximo)', value: 3000.0, category: 'TRANSFERENCIA', description: 'Art. 4o - c) Internacional - taxa CBB maxima' },
  { key: 'TRANSFERENCIA_INTERNACIONAL_FGB', label: 'Transferencia Internacional (FGB)', value: 130.0, category: 'TRANSFERENCIA', description: 'Art. 4o - c) Internacional - taxa FGB' },
  { key: 'TRANSFERENCIA_JOGO', label: 'Adiantamento/Alteracao de Jogo', value: 48.0, category: 'ARBITRAGEM', description: 'Art. 5o - Adiantamentos ou alteracoes (ginasio, horario, etc.)' },
  { key: 'CANCELAMENTO_JOGO', label: 'Cancelamento de Jogo', value: 96.0, category: 'ARBITRAGEM', description: 'Art. 6o - Cancelamento sem data definida (minimo 10 dias de antecedencia)' },
  { key: 'PROTESTO_RECURSO', label: 'Protestos, Recursos e Outros', value: 960.0, category: 'MULTA', description: 'Art. 7o - a)' },
  { key: 'MULTA_WO', label: 'Multa W.O.', value: 1920.0, category: 'MULTA', description: 'Art. 7o - b) Multa por walkover' },
  { key: 'DESISTENCIA_COMPETICAO', label: 'Desistencia de Competicao', value: 2880.0, category: 'MULTA', description: 'Art. 7o - c)' },
  { key: 'MULTA_GINASIO', label: 'Ginasio sem condicoes', value: 480.0, category: 'MULTA', description: 'Art. 7o - d) Ginasio ou dependencias sem condicoes ou nao cumprimento das Regras Oficiais' },
  { key: 'SUMULA_JOGO', label: 'Sumula (01 jogo - 3 vias)', value: 5.0, category: 'ARBITRAGEM', description: 'Art. 8o - b)' },
  { key: 'TAXA_INGRESSO_PERCENTUAL', label: 'Taxa sobre ingresso (%)', value: 10, category: 'ARBITRAGEM', description: 'Art. 9o - 10% sobre arrecadacao bruta em competicoes com cobranca de ingresso' },
] as const
